# Generated by Django 2.2.1 on 2019-05-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190515_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
            preserve_default=False,
        ),
    ]
