# Generated by Django 2.2.1 on 2019-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190516_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.TextField(default=None),
        ),
    ]
